### ISSUE TITLE
安卓运行出现问题

### ISSUE THREAD

**Issue by iptodays** [rxreader/alipay_kit#17]
![image](https://user-images.githubusercontent.com/15830996/90090997-02ad6500-dd58-11ea-925c-a516428f3b96.png)

**Comment by v7lin** [comment]
贴上你的pubspec

**Comment by iptodays** [comment]
![image](https://user-images.githubusercontent.com/15830996/90092615-f3301b00-dd5b-11ea-9ee5-5cc6e8e85183.png)

**Comment by iptodays** [comment]
有一个同事是没问题的，但是其他同事都有这个问题
