### ISSUE TITLE
Mac Android studio 进行android 调试失败，提示错误：alipaySdk-15.7.6-20200521195109.aar

### ISSUE THREAD

**Issue by Tyrone** [RxReader/alipay_kit#22]
Non-directory inputs must have .jar extension: /Users/***/flutter/.pub-cache/hosted/pub.flutter-io.cn/alipay_kit-1.1.0/android/libs/alipaySdk-15.7.6-20200521195109.aar

**Comment by Tyrone** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':alipay_kit:mergeVendorDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Non-directory inputs must have .jar extension: /Users/***/flutter/.pub-cache/hosted/pub.flutter-io.cn/alipay_kit-1.1.0/android/libs/alipaySdk-15.7.6-20200521195109.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by cody880910** [comment]
～～
