### ISSUE TITLE
Execution failed for task ':alipay_kit:processVendorDebugManifest'.

### ISSUE THREAD

**Issue by zfha** [rxreader/alipay_kit#25]
Launching lib/main.dart on VOG AL00 in debug mode...
/Users/zhoufan/flutter/.pub-cache/hosted/pub.flutter-io.cn/alipay_kit-2.0.0/android/src/vendor/AndroidManifest.xml:6:9-63 Error:
        Missing 'package' key attribute on element package at AndroidManifest.xml:6:9-63
/Users/zhoufan/flutter/.pub-cache/hosted/pub.flutter-io.cn/alipay_kit-2.0.0/android/src/vendor/AndroidManifest.xml Error:
        Validation failed, exiting                                      
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':alipay_kit:processVendorDebugManifest'.     
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Manifest merger failed with multiple errors, see logs              
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 2s                                                      
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                      2,738ms
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by zfha** [comment]
请问大神这个问题怎么解决呢， Android build失败， iOS还没测试过

**Comment by v7lin** [comment]
```groovy
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.4'
    }
}
```
