### ISSUE TITLE
编译的时候报Attribute activity#com.alipay.sdk.app.H5PayActivity@configChanges value=(orientation|keyboardHidden|navigation|screenSize) from [:alipaysdk-15.8.01.210112203525:] AndroidManifest.xml错误

### ISSUE THREAD

**Issue by StudyCat** [rxreader/alipay_kit#29]

**Comment by v7lin** [comment]
日志不全

**Comment by StudyCat** [comment]
E:\flutterApp\FuGuoMaster\android\app\src\debug\AndroidManifest.xml:29:13-85 Error:
	Attribute activity#com.alipay.sdk.app.H5PayActivity@configChanges value=(orientation|keyboardHidden|navigation|screenSize) from [:alipaysdk-15.8.01.210112203525:] AndroidManifest.xml:29:13-85
	is also present at [:alipaysdk-noutdid-15.8.01.201215151847:] AndroidManifest.xml:30:13-74 value=(orientation|keyboardHidden|navigation).
	Suggestion: add 'tools:replace="android:configChanges"' to <activity> element at AndroidManifest.xml:27:9-32:20 to override.
E:\flutterApp\FuGuoMaster\android\app\src\debug\AndroidManifest.xml:35:13-85 Error:
	Attribute activity#com.alipay.sdk.app.H5AuthActivity@configChanges value=(orientation|keyboardHidden|navigation|screenSize) from [:alipaysdk-15.8.01.210112203525:] AndroidManifest.xml:35:13-85
	is also present at [:alipaysdk-noutdid-15.8.01.201215151847:] AndroidManifest.xml:35:13-74 value=(orientation|keyboardHidden|navigation).

**Comment by v7lin** [comment]
你接了两个支付宝插件了吧！！！

**Comment by StudyCat** [comment]
接了个oss的

**Comment by StudyCat** [comment]
大神  你这个只吃oss吗

**Comment by StudyCat** [comment]
支持

**Comment by v7lin** [comment]
友尽，不送 ... OSS直接上API，傻子采用OSS插件 ...

**Comment by StudyCat** [comment]
行吧   我直接接入API吧

**Comment by StudyCat** [comment]
感谢 大神
