### ISSUE TITLE
android gradle编译失败

### ISSUE THREAD

**Issue by RA1NO3O** [rxreader/alipay_kit#31]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ra1no3o/flutter/.pub-cache/hosted/pub.dartlang.org/alipay_kit-2.2.0-nullsafety/android/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'alipay_kit'.
> Project with path ':alipay_kit' could not be found in root project 'alipay_kit'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 538ms

The plugin alipay_kit could not be built due to the issue above.

```
group 'io.github.v7lin.alipay_kit'
version '2.2.0'

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()

        // 私仓
        flatDir {
            dirs project(':alipay_kit').file('libs')
        }
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 16

        // library 混淆 -> 随 library 引用，自动添加到 apk 打包混淆
        consumerProguardFiles 'consumer-rules.pro'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    flavorDimensions 'vendor'

    productFlavors {
        vendor {
            dimension 'vendor'

            // library 混淆 -> 随 library 引用，自动添加到 apk 打包混淆
            consumerProguardFiles 'consumer-vendor-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.0.0'

    // v15.8.01
    vendorImplementation(name: 'alipaysdk-15.8.01.210112203525', ext: 'aar')
}

```

**Comment by RA1NO3O** [comment]
今早出现的，是私仓出问题了吗

**Comment by RA1NO3O** [comment]
<img width="1536" alt="截屏2021-07-20 上午10 23 01" src="https://user-images.githubusercontent.com/25654559/126252505-22d07c5d-e083-418a-9df1-c47947645150.png">

**Comment by mimiaopp** [comment]
请问解决了吗

**Comment by RA1NO3O** [comment]
> 请问解决了吗
 @mimiaopp 
解决了， 似乎是当时作者在维护吧

**Comment by mimiaopp** [comment]
> > 请问解决了吗
> 
> @mimiaopp
> 解决了， 似乎是当时作者在维护吧

我今天特出现了这个问题

**Comment by mimiaopp** [comment]
> > > 请问解决了吗
> > 
> > 
> > @mimiaopp
> > 解决了， 似乎是当时作者在维护吧
> 
> 我今天也出现了这个问题
