### ISSUE TITLE
alipay_kit: ^2.0.0 报Unhandled Exception: MissingPluginException(No implementation found for method isInstalled on channel v7lin.github.io/alipay_kit)

### ISSUE THREAD

**Issue by iptodays** [RxReader/alipay_kit#32]
![image](https://user-images.githubusercontent.com/15830996/127123103-14b87841-50a6-4897-bf7d-da3611963871.png)
使用的是pub的release版本
依赖master分支不报错

**Comment by v7lin** [comment]
看 pubspec.lock

**Comment by purgeyao** [comment]
同样问题 alipay_kit: ^2.0.0 报错
```
 异常：：══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞══════════════════════
The following MissingPluginException was thrown:
MissingPluginException(No implementation found for method pay on
channel v7lin.github.io/alipay_kit)
```

**Comment by iptodays** [comment]
> 同样问题 alipay_kit: ^2.0.0 报错
> 
> ```
>  异常：：══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞══════════════════════
> The following MissingPluginException was thrown:
> MissingPluginException(No implementation found for method pay on
> channel v7lin.github.io/alipay_kit)
> ```

2.2.0-nullsafety-Android-Only
