### ISSUE TITLE
加入的是alipay_kit pub get下来的却是 alipay_kit-2.2.0-nullsafety-Android-Only

### ISSUE THREAD

**Issue by FLEasy** [RxReader/alipay_kit#33]
现在是ios不可以使用了吗？
加入的是alipay_kit pub get下来的却是 alipay_kit-2.2.0-nullsafety-Android-Only
![image](https://user-images.githubusercontent.com/15194292/129293243-a29aafac-e9b1-42c4-a73e-f2f256d230dc.png)

**Comment by mimiaopp** [comment]
把＾去了试试

**Comment by baishitong** [comment]
目前使用2.0.0的版本？？？只能这样嘛？

**Comment by FLEasy** [comment]
@baishitong 我最后没有用这个 用了另一个的 tobias

**Comment by baishitong** [comment]
4.0.0版本完美解决。谢谢RxReader/alipay_kit.



在 2022-05-27 15:58:30，"FLEasy" ***@***.***> 写道：

Closed #33 as completed.
