### ISSUE TITLE
utdid 直接继承在alipay里 无法替换

### ISSUE THREAD

**Issue by shuigesuntao** [RxReader/alipay_kit#35]
Duplicate class com.ta.utdid2.a.a.a found in modules jetified-alipaysdk-15.8.01.210112203525-runtime (:alipaysdk-15.8.01.210112203525:) and jetified-utdid-1.5.2.1 (com.umeng.umsdk:utdid:1.5.2.1)

**Comment by v7lin** [comment]
readme看了吗？请按需修改
