### ISSUE TITLE
这个bug很牛逼 点击查看详情

### ISSUE THREAD

**Issue by mingyouzhu** [RxReader/alipay_kit#41]
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Unsupported operation: PEMKey(MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCB0M........

#0      RsaKeyParser.parsePrivate (package:alipay_kit/src/crypto/rsa.dart:29:5)
#1      RsaSigner.sha256Rsa (package:alipay_kit/src/crypto/rsa.dart:96:24)
#2      Alipay._sign (package:alipay_kit/src/alipay.dart:191:31)
#3      Alipay.auth (package:alipay_kit/src/alipay.dart:150:25)

<img width="1372" alt="Screen Shot 2022-03-08 at 2 49 42 PM" src="https://user-images.githubusercontent.com/37821420/157182648-aa9bd84f-18e5-4799-908d-27fe4145a714.png">

**Comment by v7lin** [comment]
看一下测试用例，对比一下吧
https://github.com/RxReader/alipay_kit/blob/master/test/alipay_kit_test.dart
