### ISSUE TITLE
你好，大神，alipay_kit: ^2.0.0 报Unhandled Exception: MissingPluginException(No implementation found for method isInstalled on channel v7lin.github.io/alipay_kit)

### ISSUE THREAD

**Issue by WangYiOS** [RxReader/alipay_kit#45]
我看到你回复让看 pubspec.lock

我看了，请问我要在这里更改什么内容，才能调起iOS的支付宝支付，

请帮助下我，感激不尽。

alipay_kit:
    dependency: "direct main"
    description:
      name: alipay_kit
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "4.0.0"

**Comment by v7lin** [comment]
https://github.com/RxReader/alipay_kit/tree/master/alipay_kit#flutter

**Comment by WangYiOS** [comment]
谢谢
